### ISSUE TITLE
Need a matrix of which features are compatible with others

### ISSUE THREAD

**Issue by matsen** [santa-dev/santa-sim#17]
... or some other representation.

**Comment by cswarth** [comment]
I'm not sure exactly which features we want to include in the matrix.  I took a guess and produced the following.   Odd formatting on the angled headers are due to a bug in the excel clone [libreoffice#59511](https://bugs.documentfoundation.org/show_bug.cgi?id=59511); wil be fixed in final version.

Are there other features we would like to capture?

![screen shot 2016-08-09 at 4 14 39 pm](https://cloud.githubusercontent.com/assets/295428/17536914/7cd81548-5e4d-11e6-876b-c55a3212cc27.png)

**Comment by matsen** [comment]
This is great!

**Comment by matsen** [comment]
(don't forget to close!)
