### ISSUE TITLE
Version one-point-oh!

### ISSUE THREAD

**Issue by matsen** [santa-dev/santa-sim#19]
Let's cut a release when all the issues are done! 🎉

**Comment by slequime** [comment]
Almost a year later... Any updates on potential release? Is someone still working on it (or has in mind to work on it)? 
I'm verry interested in using SantaSim in some of my projects (already used it a little bit), but some aspects are still a little obscure.

**Comment by matsen** [comment]
Some of the team has moved on. Can you describe what's obscure / raise some issues though?

**Comment by slequime** [comment]
I was mostly wondering if the population dynamics aspect was implemented. I saw some code for exponential/logistic population dynamics, but I have no idea if they are usable yet and if yes how to use them (java is still quite foreign for me...). I saw that the StaticPopulation has been used in several examples though.

**Comment by abbasjariani** [comment]
Hi, I am glad to  hear about your interest in the software. A dynamic population model of logistic growth is implemented, however we are lacking for examples and documentations for this aspect. Here is a short description how to use it. I will update the wiki when I am back from holidays.

In order to use the logistic growth model, in the input xml file you should have an entry, where you set the variable "populationType" to "dynamicPopulation"

you could see an example how this variable should be introduced in [this example](https://github.com/santa-dev/santa-sim/blob/master/examples/simpleRecombination.xml) where "populationType" is set to "staticPopulation".

At the moment the parameters for this model i.e. growth rate and carrying population size could only be set through the source code [in this file](https://github.com/santa-dev/santa-sim/blob/master/src/santa/simulator/selectors/DynamicSelector.java) and not through the input xml file. Sorry about this shortage. After setting the parameter of your choices you would need to build the project again using 'ant'.

Please let us know if you try this and if you find a set of parameters that work nicely for you so we could add it as an example.
